# Agricultural Finance -- Introduction-Scope and Definition

Agricultural finance generally means studying, examining and analyzing
the financial aspects pertaining to farm business, which is the core
sector of India. The financial aspects include money matters relating to
production of agricultural products and their disposal.

## Problems of Agricultural Credit in India

-   Mass illiteracy coupled with subsistence nature of farming
    discourage farmers to took it as a business. Absence of farm records
    make it difficult to evolve lending policy.

-   Diversion of production loan to consumption purpose

-   In the absence of institutional agencies money lenders acquire
    monopoly status.

## Need for credit

-   Expenditure pattern of small and marginal reveals that they hardly
    any savings .

    Very few farmers have capital to invest in agriculture.

## Definition of Agricultural finance

Tandon and Dhondyal (1962) defined agricultural finance "as a branch of
agricultural economics, which deals with provision and management of
bank services and financial resources related to individual farm units".

The following are implied in the above definition

1.  All the farmers should be given requisite finance.

2.  Finance should stimulate and enhance productivity of scarce farm
    resources.

3.  Farm finance has a vital and catalytic role for agro economic
    development of farmers.

**Nature and Scope:**

Agricultural finance can be dealt at both **micro level and macro
level**.

### Macro finance  
Deals with different sources of raising funds for
agriculture as a whole in the economy. It is also concerned with the
lending procedure, rules, regulations, monitoring and controlling of
different agricultural credit institutions. Hence macro-finance is
related to financing of agriculture at aggregate level.

## Micro-finance  
Refers to financial management of the individual farm
business units and it is concerned with the study as to how the
individual farmer considers various sources of credit, quantum of credit
to be borrowed from each source and how he allocates the same among the
alternative uses with in the farm. It is also concerned with the future
use of funds

> Therefore, macro-finance deals with the aspects relating to total credit needs of the agricultural sector, the terms and conditions under
which the credit is available and the method of use of total credit for
the development of agriculture, while micro-finance refers to the
financial management of individual farm business.

  **Macrofinance**                                                                                                                                                                                                          **Microfinance**
  ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Deals with the different sources of raising funds for agriculture as a whole in the economy                                                                                                                               Refers to financial management of the individual farm business units.
  It is concerned with the lending procedures, rules, regulations, monitoring and controlling procedures of different agricultural credit institutions                                                                      It is concerned with the future use of funds.
  Related to financing of agriculture at aggregate level.                                                                                                                                                                   Refers to the financial management of individual farm business.
  Deals with the aspects relating to total credit needs of the agricultural sector, the terms and conditions under which the credit is available and the method of use of total credit for the development of agriculture   Concerned with the study as to how the individual farmer considers various sources of credit, quantum of credit to be borrowed from each source and how he allocates the same among the alternative uses with in the farm

## Significance/ Importance of Agricultural Finance

1\) Agril finance assumes vital and significant importance in the agro
-- socio -- economic development of the country both at macro/aggregate
and micro/individual level.

2\) It is playing a catalytic role in strengthening the farm business
and augmenting the productivity of scarce resources. When newly
developed potential seeds are combined with purchased inputs like
fertilizers & plant protection chemicals in appropriate / requisite
proportions will result in higher productivity.

3\) Use of new technological inputs purchased through farm finance helps
to increase the agricultural productivity.

4\) Accretion to in farm assets and farm supporting infrastructure
provided by large scale financial investment activities results in
increased farm income levels leading to increased standard of living of
rural masses.

5\) Farm finance can also reduce the regional economic imbalances and is
equally good at reducing the inter--farm asset and wealth variations.

6\) Farm finance is like a lever with both forward and backward linkages
to the economic development at micro and macro level.

7\) As Indian agriculture is still traditional and subsistence in
nature, agricultural finance is needed to create the supporting
infrastructure for adoption of new technology.

8\) Massive investment is needed to carry out major and minor irrigation
projects, rural electrification, installation of fertilizer and
pesticide plants, execution of agricultural promotional programmes and
poverty alleviation programmes in the country.

>Thus agricultural finance is not just a science to manage the money but
is an applied science of allocating scarce resources to derive optimum
output. The role of agrl financing strengthening and developing input
and output market is crucial and important.

Farm financial management deals with the acquisition and use of credit.
The farm financial management decisions are

1.  Decisions regarding requisite capital

2.  Decisions regarding source of capital.

3.  Decision regarding allocation of capital among the alternatives

4.  Decision strategies to be adopted to counter risk and uncertainty

5.  Decisions on legal problems relating to farm organisation and
    operation  

## Agricultural Credit  
The word "credit" comes from the Latin word "Credo" which means "I
believe". Hence credit is based up on belief, confidence, trust and
faith. Credit is otherwise called as loan.  

### Definition  

Credit / loan
is certain amount of money provided for certain purpose on certain
conditions with some interest, which can be repaid sooner (or) later.
According to Professor Galbraith credit is the "temporary transfer of
asset from one who has to other who has not".

Agricultural Credit is the amount of money made available for
agricultural production from resources outside the farm sector.
Agricultural Credit is defined as a type of financing used to provide
funding for agricultural producers. This may be in the form of letters
of credit, loans or banker's acceptance documents. This is generally
used to provide investment from outside resources to the farming sector.

>Agricultural Finance is considered as separate field of study dealing
with lending and borrowing by organizations and farmers

## Credit needs in Agriculture  
Agricultural credit is one of the most
crucial inputs in all agricultural development programmes. For a long
time, the major source of agricultural credit was private moneylenders.
But this source of credit was inadequate, highly expensive and
exploitative. To curtail this, a multi-agency approach consisting of
cooperatives, commercial banks and regional rural banks credit has been
adopted to provide cheaper, timely and adequate credit to farmers. The
financial requirements of the Indian farmers are for,

1.  Buying agricultural inputs like seeds, fertilizers, plant protection
    chemicals, feed and fodder for cattle etc.

2.  Supporting their families in those years when the crops have not
    been good.

3.  Buying additional land, to make improvements on the existing land,
    to clear old debt and purchase costly agricultural machinery.

4.  Increasing the farm efficiency as against limiting resources i.e.
    hiring of irrigation water lifting devices, labor and machinery.
